staging:
  deploy_to: "/aytomad/app/ancar_areas"
  ssh_port: 22
  server: "rorappdesa08A.munimadrid.es"
  user: "deploy"
  db_server: "pgcorpdesa01.munimadrid.es"
  db_name: "ancar_areas"
  db_user: "ancar_areas_owner"
