staging:
  deploy_to: "/aytomad/app/ancar_areas/ancar_areas"
  ssh_port: 22
  server: "rorappdesa08A.munimadrid.es"
  user: "deploy"
  db_server: "pgcorpdesa01.munimadrid.es"
  db_name: "ancar_areas"
  db_user: "ancar_areas_owner"

preproduction:
  deploy_to: "/aytomad/app/ancar_areas/ancar_areas"
  ssh_port: 22
  server1: "rorapppre08A.munimadrid.es"
  server2: "rorapppre08B.munimadrid.es"
  user: "deploy"
  db_server: "pgcorppre01.munimadrid.es"
  db_name: "ancar_areas"
  db_user: "ancar_areas_owner"

production:
  deploy_to: "/aytomad/app/ancar_areas/ancar_areas"
  ssh_port: 22
  server: "rorapppro08A.munimadrid.es"
  user: "deploy"
  db_server: "pgcorppro01.munimadrid.es"
  db_name: "ancar_areas"
  db_user: "ancar_areas_owner"