# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  uweb_wsdl: http://intranet.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl
  uweb_application_key: 292
  uweb_update_wsdl: http://intranet.munimadrid.es:8090/WSUwebUpdate/services/ServicesUweb?wsdl
  uweb_update_key: 33
  uweb_update_pwd: 'AncarRor'
  uweb_update_app: 292
  uweb_update_profile: 1541
  uweb_update_key_profile_connect: 1541
  secret_key_base: c55ab9c1b47160322480cb8ebb323cc2f3284969c3fd883fa0554cf07fac3fb7fa2757eb92c118838cbb749f7684130b90c48bbcd564c5d70714e0f705364c75
  default_email_sender: 'noreply@madrid.es'
  server_name_mail: 'correo.munimadrid.es'
  server_name: 'voluntariospormadridpre.madrid.es'
  directorio_wsdl: http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl
  directorio_application_key: 'ANCAR'

staging:
  uweb_wsdl: http://intranet.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl
  uweb_application_key: 292
  uweb_update_wsdl: http://intranet.munimadrid.es:8090/WSUwebUpdate/services/ServicesUweb?wsdl
  uweb_update_key: 35
  uweb_update_pwd: 'AncarRor'
  uweb_update_app: 310
  uweb_update_profile: 1651
  uweb_update_key_profile_connect:  1651
  secret_key_base: c55ab9c1b47160322480cb8ebb323cc2f3284969c3fd883fa0554cf07fac3fb7fa2757eb92c118838cbb749f7684130b90c48bbcd564c5d70714e0f705364c75
  default_email_sender: 'noreply@madrid.es'
  server_name_mail: 'correo.munimadrid.es'
  server_name: 'voluntariospormadridpre.madrid.es'
  directorio_wsdl: http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl
  directorio_application_key: 'ANCAR'

test:
  secret_key_base: ae770c756967c5fd70579e972a77dc23da17db603a1915cc43fd16b3a3fdf181e719dfbcf81eed91ba4d83b106632511336066ac546c98734a490d5958eaa6b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
preproduction:
  uweb_wsdl: http://intranet.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl
  uweb_application_key: 292
  uweb_update_wsdl: http://intranet.munimadrid.es:8090/WSUwebUpdate/services/ServicesUweb?wsdl
  uweb_update_key: 35
  uweb_update_pwd: 'AncarRor'
  uweb_update_app: 310
  uweb_update_profile: 1651
  uweb_update_key_profile_connect:  1651
  secret_key_base: c55ab9c1b47160322480cb8ebb323cc2f3284969c3fd883fa0554cf07fac3fb7fa2757eb92c118838cbb749f7684130b90c48bbcd564c5d70714e0f705364c75
  default_email_sender: 'noreply@madrid.es'
  server_name_mail: 'correo.munimadrid.es'
  server_name: 'voluntariospormadridpre.madrid.es'
  directory_wsdl: http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl
  directorio_application_key: 'ANCAR'

production:
  uweb_wsdl: http://intranet.munimadrid.es:8090/WSUwebv2/services/ServicesUweb?wsdl
  uweb_application_key: 292
  uweb_update_wsdl: http://intranet.munimadrid.es:8090/WSUwebUpdate/services/ServicesUweb?wsdl
  uweb_update_key: 34
  uweb_update_pwd: 'AncarRor'
  uweb_update_app: 309
  uweb_update_profile: 1655
  uweb_update_key_profile_connect:  1655
  secret_key_base: c55ab9c1b47160322480cb8ebb323cc2f3284969c3fd883fa0554cf07fac3fb7fa2757eb92c118838cbb749f7684130b90c48bbcd564c5d70714e0f705364c75
  default_email_sender: 'noreply@madrid.es'
  server_name_mail: 'correo.munimadrid.es'
  server_name: 'voluntariospormadridpre.madrid.es'
  directory_wsdl: http://intranet.munimadrid.es:8090/DirectorioWS/services/Directorio/wsdl/Directorio.wsdl
  directorio_application_key: 'ANCAR'
